# docker build --tag "149736408060.dkr.ecr.ap-south-1.amazonaws.com/varca-app:pit-api" --file ops/images/Dockerfile.varca-pit-api .

FROM 149736408060.dkr.ecr.ap-south-1.amazonaws.com/varca-app:base

RUN mkdir -p /app/configs

RUN cp -r /varca/hosts/Varca.Pit.API/bin/Release/net8.0/publish/* /app
RUN cp -r /varca/configs/* /app/configs


WORKDIR /app
ENTRYPOINT ["dotnet", "Varca.Pit.API.dll"]
