---

geoDb:
  type: elasticsearch
  apikey: 'UGpqY05vNEJwRVo4cVAwUVdVYnY6OUlPNWk2ZFBUdS12V3lLSVlJU0xlQQ=='
  ca: 'bb8f570cb2c7d839d90107a4621f49da9d755432c7abcacc7a6839741fc40333'
  nodes:
    - https://localhost:9200
  hotelGeoDb: varca-search-hotel-geo-db-v1
  placeGeoDb: varca-place-geo-db-v1

migrationDb:
  type: mongodb
  url: 'mongodb://app:vervozaq1ZAQ!@mongo-core-0.mapping.vervotech.com:27017/admin?authMechanism=SCRAM-SHA-1&directConnection=true'

